spring:
  profiles:
    active: dev
  jackson:
    serialization.indent_output: true
  datasource:
    url: jdbc:mysql://localhost:3306/musicmax
    username: root
    password: Ivana12!

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      dll-auto: create
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true